import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Layout from "@/components/layout/Layout";

const roboto = Roboto({ weight:['100','400','700','900'],subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WEB AO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Layout>{children}</Layout></body>
    </html>
  );
}
